### ISSUE TITLE
Improve the demo to showcase the benefit of your Defer

### ISSUE THREAD

**Issue by taeber** [moon-chilled/Defer#3]
I saw your code on [Hacker News](https://news.ycombinator.com/item?id=22613950). I too like Go's `defer` statements so I appreciate your attempt at recreating it in C.

I don't think your demo code really demonstrates the benefit of it, however.

For comparison, here is the equivalent code rewritten without your defer additions which looks pretty straightforward and more readily understood:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void test1(void) {
	char *x = malloc(0x100);
	strcpy(x, "Hello world");

	printf("x is %s\n", x);
	x[1]++;
	printf("now %s\n", x);
	free(x);
}

int test2(void) {
	puts("1");
	puts("2");
	return puts("3");
}

int main(void) {
	test1();
	return test2();
}
```

Could you write a version of `demo.c` that better showcases the benefits of Defer? Thank you.

**Comment by moon-chilled** [comment]
It's not really practical to show in such a small example.  The whole reason `defer` is desirable is because it makes it easier to manage lifetimes in complex functions with multiple exits.

The purpose of the example is mostly just to clarify the semantics.
